-- وكالة إسحاق العالمية
-- Run this file once in Supabase Dashboard → SQL Editor.

begin;

create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  payload jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint primary key,
  name text not null,
  family text not null default '',
  image text not null,
  category text not null,
  type text not null default '',
  size text not null default '',
  badge text,
  price text,
  description text not null default '',
  features jsonb not null default '[]'::jsonb,
  printer_page_content jsonb,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint products_features_is_array check (jsonb_typeof(features) = 'array'),
  constraint products_printer_page_content_is_object check (
    printer_page_content is null or jsonb_typeof(printer_page_content) = 'object'
  )
);

create table if not exists public.hero_slides (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text not null default '',
  description text not null,
  badge_text text not null default '',
  image_url text not null,
  image_alt text not null default '',
  primary_button_text text not null default '',
  primary_button_url text not null default '',
  secondary_button_text text not null default '',
  secondary_button_url text not null default '',
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hero_settings (
  id integer primary key default 1 check (id = 1),
  autoplay_enabled boolean not null default true,
  autoplay_delay integer not null default 5000 check (autoplay_delay between 1000 and 30000),
  show_arrows boolean not null default true,
  show_dots boolean not null default true,
  pause_on_hover boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_sort_order_idx on public.products (sort_order, id);
create index if not exists hero_slides_display_order_idx on public.hero_slides (display_order, id);
create index if not exists hero_slides_active_order_idx on public.hero_slides (is_active, display_order, id);

alter table public.site_settings enable row level security;
alter table public.products enable row level security;
alter table public.hero_slides enable row level security;
alter table public.hero_settings enable row level security;

-- Browser clients receive no direct table permissions. All reads and writes pass
-- through authenticated Next.js Route Handlers using the server-only service key.
revoke all on table public.site_settings from anon, authenticated;
revoke all on table public.products from anon, authenticated;
revoke all on table public.hero_slides from anon, authenticated;
revoke all on table public.hero_settings from anon, authenticated;

grant select, insert, update, delete on table public.site_settings to service_role;
grant select, insert, update, delete on table public.products to service_role;
grant select, insert, update, delete on table public.hero_slides to service_role;
grant select, insert, update, delete on table public.hero_settings to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Replaces settings and products in one PostgreSQL transaction so a failed product
-- write cannot leave the site with an empty product list.
create or replace function public.replace_site_data(
  p_settings jsonb,
  p_products jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.site_settings (id, payload, updated_at)
  values (1, coalesce(p_settings, '{}'::jsonb), now())
  on conflict (id) do update
    set payload = excluded.payload,
        updated_at = excluded.updated_at;

  delete from public.products where id is not null;

  insert into public.products (
    id, name, family, image, category, type, size, badge, price,
    description, features, printer_page_content, sort_order, created_at, updated_at
  )
  select
    item.id,
    item.name,
    coalesce(item.family, ''),
    item.image,
    item.category,
    coalesce(item.type, ''),
    coalesce(item.size, ''),
    nullif(item.badge, ''),
    nullif(item.price, ''),
    coalesce(item.description, ''),
    coalesce(item.features, '[]'::jsonb),
    item.printer_page_content,
    coalesce(item.sort_order, 0),
    now(),
    now()
  from jsonb_to_recordset(coalesce(p_products, '[]'::jsonb)) as item(
    id bigint,
    name text,
    family text,
    image text,
    category text,
    type text,
    size text,
    badge text,
    price text,
    description text,
    features jsonb,
    printer_page_content jsonb,
    sort_order integer
  );
end;
$$;

revoke all on function public.replace_site_data(jsonb, jsonb) from public, anon, authenticated;
grant execute on function public.replace_site_data(jsonb, jsonb) to service_role;

-- Idempotent copy corrections for existing records. Legacy hero fields are removed
-- because public.hero_slides is the only source used by the main banner.
update public.site_settings
set payload = payload
  - 'heroEyebrow'
  - 'heroTitle'
  - 'heroHighlight'
  - 'heroDescription'
  - 'heroImage'
where id = 1;

update public.site_settings
set payload = jsonb_set(
  jsonb_set(
    payload,
    '{maintenanceDescription}',
    to_jsonb('للفحص والصيانة والدعم الفني، اختر أحد الرقمين، وسيُفتح تطبيق واتساب أو تطبيق الاتصال مباشرة على جهازك.'::text),
    true
  ),
  '{address}',
  to_jsonb('صنعاء – شارع صخر من جهة الدائري'::text),
  true
) || jsonb_build_object(
  'workWeekdays', coalesce(payload ->> 'workWeekdays', 'sat,sun,mon,tue,wed,thu'),
  'workStartTime', coalesce(payload ->> 'workStartTime', '09:30'),
  'workEndTime', coalesce(payload ->> 'workEndTime', '22:00')
)
where id = 1
  and (
    payload ->> 'maintenanceDescription' ~ 'اختر أحد الرقمين وسيفتح واتساب'
    or payload ->> 'address' ~ 'من جهة[[:space:]]*\\(الدائري\\)'
    or not (payload ?& array['workWeekdays', 'workStartTime', 'workEndTime'])
  );

update public.hero_slides
set title = regexp_replace(title, 'تقنيات وحلول[[:space:]]{2}كبرى', 'تقنيات وحلول متكاملة', 'g'),
    subtitle = regexp_replace(subtitle, 'الإكسسوارات[[:space:]]+الإلكترونية', 'الملحقات الإلكترونية', 'g'),
    description = regexp_replace(description, 'الإكسسوارات[[:space:]]+الإلكترونية', 'الملحقات الإلكترونية', 'g'),
    badge_text = regexp_replace(badge_text, 'الإكسسوارات[[:space:]]+الإلكترونية', 'الملحقات الإلكترونية', 'g'),
    updated_at = now()
where title ~ 'تقنيات وحلول[[:space:]]{2}كبرى'
   or subtitle ~ 'الإكسسوارات[[:space:]]+الإلكترونية'
   or description ~ 'الإكسسوارات[[:space:]]+الإلكترونية'
   or badge_text ~ 'الإكسسوارات[[:space:]]+الإلكترونية';

update public.products
set name = regexp_replace(name, '^Epson([[:space:]])', 'EPSON\1'),
    updated_at = now()
where name ~ '^Epson[[:space:]]';

-- Public bucket for website images. Upload/delete operations still use the
-- server-only service key through /api/upload.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'site-media',
  'site-media',
  true,
  4194304,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

commit;
