-- وكالة إسحاق العالمية
-- Run this file once in Supabase Dashboard → SQL Editor.

begin;

create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  payload jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint primary key,
  name text not null,
  family text not null default '',
  image text not null,
  category text not null,
  type text not null default '',
  size text not null default '',
  badge text,
  price text,
  description text not null default '',
  features jsonb not null default '[]'::jsonb,
  printer_page_content jsonb,
  sort_order integer not null default 0,
  home_display_order integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint products_features_is_array check (jsonb_typeof(features) = 'array'),
  constraint products_printer_page_content_is_object check (
    printer_page_content is null or jsonb_typeof(printer_page_content) = 'object'
  ),
  constraint products_home_display_order_nonnegative check (
    home_display_order is null or home_display_order >= 0
  )
);

create table if not exists public.hero_slides (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text not null default '',
  description text not null,
  badge_text text not null default '',
  image_url text not null,
  image_alt text not null default '',
  primary_button_text text not null default '',
  primary_button_url text not null default '',
  secondary_button_text text not null default '',
  secondary_button_url text not null default '',
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hero_settings (
  id integer primary key default 1 check (id = 1),
  autoplay_enabled boolean not null default true,
  autoplay_delay integer not null default 5000 check (autoplay_delay between 1000 and 30000),
  show_arrows boolean not null default true,
  show_dots boolean not null default true,
  pause_on_hover boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_sort_order_idx on public.products (sort_order, id);
create index if not exists products_home_display_order_idx
  on public.products (home_display_order asc nulls last, sort_order, id);
create index if not exists hero_slides_display_order_idx on public.hero_slides (display_order, id);
create index if not exists hero_slides_active_order_idx on public.hero_slides (is_active, display_order, id);

alter table public.site_settings enable row level security;
alter table public.products enable row level security;
alter table public.hero_slides enable row level security;
alter table public.hero_settings enable row level security;

-- Browser clients receive no direct table permissions. All reads and writes pass
-- through authenticated Next.js Route Handlers using the server-only service key.
revoke all on table public.site_settings from anon, authenticated;
revoke all on table public.products from anon, authenticated;
revoke all on table public.hero_slides from anon, authenticated;
revoke all on table public.hero_settings from anon, authenticated;

grant select, insert, update, delete on table public.site_settings to service_role;
grant select, insert, update, delete on table public.products to service_role;
grant select, insert, update, delete on table public.hero_slides to service_role;
grant select, insert, update, delete on table public.hero_settings to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Replaces settings and products in one PostgreSQL transaction so a failed product
-- write cannot leave the site with an empty product list.
create or replace function public.replace_site_data(
  p_settings jsonb,
  p_products jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.site_settings (id, payload, updated_at)
  values (1, coalesce(p_settings, '{}'::jsonb), now())
  on conflict (id) do update
    set payload = excluded.payload,
        updated_at = excluded.updated_at;

  delete from public.products where id is not null;

  insert into public.products (
    id, name, family, image, category, type, size, badge, price,
    description, features, printer_page_content, sort_order, home_display_order, created_at, updated_at
  )
  select
    item.id,
    item.name,
    coalesce(item.family, ''),
    item.image,
    item.category,
    coalesce(item.type, ''),
    coalesce(item.size, ''),
    nullif(item.badge, ''),
    nullif(item.price, ''),
    coalesce(item.description, ''),
    coalesce(item.features, '[]'::jsonb),
    item.printer_page_content,
    coalesce(item.sort_order, 0),
    item.home_display_order,
    now(),
    now()
  from jsonb_to_recordset(coalesce(p_products, '[]'::jsonb)) as item(
    id bigint,
    name text,
    family text,
    image text,
    category text,
    type text,
    size text,
    badge text,
    price text,
    description text,
    features jsonb,
    printer_page_content jsonb,
    sort_order integer,
    home_display_order integer
  );
end;
$$;

revoke all on function public.replace_site_data(jsonb, jsonb) from public, anon, authenticated;
grant execute on function public.replace_site_data(jsonb, jsonb) to service_role;

create or replace function public.set_home_product_order(p_items jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  expected_count integer;
  updated_count integer;
begin
  if jsonb_typeof(coalesce(p_items, '[]'::jsonb)) is distinct from 'array' then
    raise exception 'home product order must be a JSON array';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(coalesce(p_items, '[]'::jsonb)) as item(
      id bigint,
      category text,
      home_display_order integer
    )
    where item.id is null
      or item.category not in ('printers', 'papers', 'inks')
      or item.home_display_order is null
      or item.home_display_order < 0
  ) or exists (
    select 1
    from jsonb_to_recordset(coalesce(p_items, '[]'::jsonb)) as item(
      id bigint,
      category text,
      home_display_order integer
    )
    group by item.id
    having count(*) > 1
  ) or exists (
    select 1
    from jsonb_to_recordset(coalesce(p_items, '[]'::jsonb)) as item(
      id bigint,
      category text,
      home_display_order integer
    )
    group by item.category, item.home_display_order
    having count(*) > 1
  ) then
    raise exception 'invalid or duplicate home product order item';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(coalesce(p_items, '[]'::jsonb)) as item(
      id bigint,
      category text,
      home_display_order integer
    )
    group by item.category
    having min(item.home_display_order) <> 0
      or max(item.home_display_order) <> count(*) - 1
  ) then
    raise exception 'home product order must be contiguous in every category';
  end if;

  select count(*) into expected_count
  from public.products
  where category in ('printers', 'workforce', 'ecotank', 'ecotank-6-color', 'lq', 'papers', 'inks');

  if jsonb_array_length(coalesce(p_items, '[]'::jsonb)) <> expected_count
    or exists (
      select 1
      from jsonb_to_recordset(coalesce(p_items, '[]'::jsonb)) as item(
        id bigint,
        category text,
        home_display_order integer
      )
      left join public.products as product on product.id = item.id
      where product.id is null
        or case
          when product.category in ('printers', 'workforce', 'ecotank', 'ecotank-6-color', 'lq') then 'printers'
          else product.category
        end <> item.category
    )
  then
    raise exception 'home product order does not match current public products';
  end if;

  update public.products as product
  set home_display_order = item.home_display_order,
      updated_at = now()
  from jsonb_to_recordset(coalesce(p_items, '[]'::jsonb)) as item(
    id bigint,
    category text,
    home_display_order integer
  )
  where product.id = item.id;

  get diagnostics updated_count = row_count;
  if updated_count <> expected_count then
    raise exception 'home product order update was incomplete';
  end if;
end;
$$;

revoke all on function public.set_home_product_order(jsonb) from public, anon, authenticated;
grant execute on function public.set_home_product_order(jsonb) to service_role;

-- Idempotent copy corrections for existing records. Legacy hero fields are removed
-- because public.hero_slides is the only source used by the main banner.
update public.site_settings
set payload = payload
  - 'heroEyebrow'
  - 'heroTitle'
  - 'heroHighlight'
  - 'heroDescription'
  - 'heroImage'
where id = 1;

update public.site_settings
set payload = jsonb_set(
  jsonb_set(
    payload,
    '{maintenanceDescription}',
    to_jsonb('للفحص والصيانة والدعم الفني، اختر أحد الرقمين، وسيُفتح تطبيق واتساب أو تطبيق الاتصال مباشرة على جهازك.'::text),
    true
  ),
  '{address}',
  to_jsonb('صنعاء – شارع صخر من جهة الدائري'::text),
  true
) || jsonb_build_object(
  'workWeekdays', coalesce(payload ->> 'workWeekdays', 'sat,sun,mon,tue,wed,thu'),
  'workStartTime', coalesce(payload ->> 'workStartTime', '09:30'),
  'workEndTime', coalesce(payload ->> 'workEndTime', '22:00')
)
where id = 1
  and (
    payload ->> 'maintenanceDescription' ~ 'اختر أحد الرقمين وسيفتح واتساب'
    or payload ->> 'address' ~ 'من جهة[[:space:]]*\\(الدائري\\)'
    or not (payload ?& array['workWeekdays', 'workStartTime', 'workEndTime'])
  );

update public.hero_slides
set title = regexp_replace(title, 'تقنيات وحلول[[:space:]]{2}كبرى', 'تقنيات وحلول متكاملة', 'g'),
    subtitle = regexp_replace(subtitle, 'الإكسسوارات[[:space:]]+الإلكترونية', 'الملحقات الإلكترونية', 'g'),
    description = regexp_replace(description, 'الإكسسوارات[[:space:]]+الإلكترونية', 'الملحقات الإلكترونية', 'g'),
    badge_text = regexp_replace(badge_text, 'الإكسسوارات[[:space:]]+الإلكترونية', 'الملحقات الإلكترونية', 'g'),
    updated_at = now()
where title ~ 'تقنيات وحلول[[:space:]]{2}كبرى'
   or subtitle ~ 'الإكسسوارات[[:space:]]+الإلكترونية'
   or description ~ 'الإكسسوارات[[:space:]]+الإلكترونية'
   or badge_text ~ 'الإكسسوارات[[:space:]]+الإلكترونية';

update public.products
set name = regexp_replace(name, '^Epson([[:space:]])', 'EPSON\1'),
    updated_at = now()
where name ~ '^Epson[[:space:]]';

-- Public bucket for website images. Upload/delete operations still use the
-- server-only service key through /api/upload.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'site-media',
  'site-media',
  true,
  4194304,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.product_models (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  model text not null,
  part_number text,
  color text,
  compatibility text,
  availability text not null default 'on_request' check (availability in ('in_stock', 'out_of_stock', 'on_request')),
  price text,
  image text,
  sort_order integer not null default 0 check (sort_order >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_id, model),
  check (btrim(model) <> '')
);
create index if not exists product_models_product_sort_idx on public.product_models (product_id, sort_order, id);
create unique index if not exists product_models_product_model_ci_uidx on public.product_models (product_id, lower(model));
create index if not exists product_models_active_product_sort_idx on public.product_models (product_id, sort_order, id) where is_active;
create index if not exists product_models_part_number_idx on public.product_models (part_number) where part_number is not null;
alter table public.product_models enable row level security;
revoke all on table public.product_models from anon, authenticated;
grant select, insert, update, delete on table public.product_models to service_role;
grant usage, select on sequence public.product_models_id_seq to service_role;

create or replace function public.replace_product_models(p_product_id bigint, p_models jsonb)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not exists (select 1 from public.products where id = p_product_id) then
    raise exception 'Product % does not exist', p_product_id;
  end if;
  delete from public.product_models where product_id = p_product_id;
  insert into public.product_models (product_id, model, part_number, color, compatibility, availability, price, image, sort_order, is_active)
  select p_product_id, btrim(item.model), nullif(btrim(item.part_number), ''), nullif(btrim(item.color), ''), nullif(btrim(item.compatibility), ''),
    coalesce(nullif(item.availability, ''), 'on_request'), nullif(btrim(item.price), ''), nullif(btrim(item.image), ''),
    coalesce(item.sort_order, entry.ordinality - 1), coalesce(item.is_active, true)
  from jsonb_array_elements(coalesce(p_models, '[]'::jsonb)) with ordinality as entry(value, ordinality)
  cross join lateral jsonb_to_record(entry.value) as item(model text, part_number text, color text, compatibility text, availability text, price text, image text, sort_order integer, is_active boolean);
end;
$$;
revoke all on function public.replace_product_models(bigint, jsonb) from public, anon, authenticated;
grant execute on function public.replace_product_models(bigint, jsonb) to service_role;

commit;
