-- وكالة إسحاق العالمية
-- Run this file once in Supabase Dashboard → SQL Editor.

begin;

create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  payload jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint primary key,
  name text not null,
  family text not null default '',
  image text not null,
  category text not null,
  type text not null default '',
  size text not null default '',
  badge text,
  price text,
  description text not null default '',
  features jsonb not null default '[]'::jsonb,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint products_features_is_array check (jsonb_typeof(features) = 'array')
);

create table if not exists public.hero_slides (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text not null default '',
  description text not null,
  badge_text text not null default '',
  image_url text not null,
  image_alt text not null default '',
  primary_button_text text not null default '',
  primary_button_url text not null default '',
  secondary_button_text text not null default '',
  secondary_button_url text not null default '',
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hero_settings (
  id integer primary key default 1 check (id = 1),
  autoplay_enabled boolean not null default true,
  autoplay_delay integer not null default 5000 check (autoplay_delay between 1000 and 30000),
  show_arrows boolean not null default true,
  show_dots boolean not null default true,
  pause_on_hover boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_sort_order_idx on public.products (sort_order, id);
create index if not exists hero_slides_display_order_idx on public.hero_slides (display_order, id);
create index if not exists hero_slides_active_order_idx on public.hero_slides (is_active, display_order, id);

alter table public.site_settings enable row level security;
alter table public.products enable row level security;
alter table public.hero_slides enable row level security;
alter table public.hero_settings enable row level security;

-- Browser clients receive no direct table permissions. All reads and writes pass
-- through authenticated Next.js Route Handlers using the server-only service key.
revoke all on table public.site_settings from anon, authenticated;
revoke all on table public.products from anon, authenticated;
revoke all on table public.hero_slides from anon, authenticated;
revoke all on table public.hero_settings from anon, authenticated;

grant select, insert, update, delete on table public.site_settings to service_role;
grant select, insert, update, delete on table public.products to service_role;
grant select, insert, update, delete on table public.hero_slides to service_role;
grant select, insert, update, delete on table public.hero_settings to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Replaces settings and products in one PostgreSQL transaction so a failed product
-- write cannot leave the site with an empty product list.
create or replace function public.replace_site_data(
  p_settings jsonb,
  p_products jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.site_settings (id, payload, updated_at)
  values (1, coalesce(p_settings, '{}'::jsonb), now())
  on conflict (id) do update
    set payload = excluded.payload,
        updated_at = excluded.updated_at;

  delete from public.products;

  insert into public.products (
    id, name, family, image, category, type, size, badge, price,
    description, features, sort_order, created_at, updated_at
  )
  select
    item.id,
    item.name,
    coalesce(item.family, ''),
    item.image,
    item.category,
    coalesce(item.type, ''),
    coalesce(item.size, ''),
    nullif(item.badge, ''),
    nullif(item.price, ''),
    coalesce(item.description, ''),
    coalesce(item.features, '[]'::jsonb),
    coalesce(item.sort_order, 0),
    now(),
    now()
  from jsonb_to_recordset(coalesce(p_products, '[]'::jsonb)) as item(
    id bigint,
    name text,
    family text,
    image text,
    category text,
    type text,
    size text,
    badge text,
    price text,
    description text,
    features jsonb,
    sort_order integer
  );
end;
$$;

revoke all on function public.replace_site_data(jsonb, jsonb) from public, anon, authenticated;
grant execute on function public.replace_site_data(jsonb, jsonb) to service_role;

-- Public bucket for website images. Upload/delete operations still use the
-- server-only service key through /api/upload.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'site-media',
  'site-media',
  true,
  4194304,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

commit;
