create table if not exists public.product_models (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  model text not null,
  part_number text,
  color text,
  compatibility text,
  availability text not null default 'on_request',
  price text,
  image text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_models_model_not_blank check (btrim(model) <> ''),
  constraint product_models_availability_valid check (availability in ('in_stock', 'out_of_stock', 'on_request')),
  constraint product_models_sort_order_nonnegative check (sort_order >= 0),
  constraint product_models_product_model_unique unique (product_id, model)
);

create index if not exists product_models_product_sort_idx on public.product_models (product_id, sort_order, id);
create unique index if not exists product_models_product_model_ci_uidx on public.product_models (product_id, lower(model));
create index if not exists product_models_active_product_sort_idx on public.product_models (product_id, sort_order, id) where is_active;
create index if not exists product_models_part_number_idx on public.product_models (part_number) where part_number is not null;

alter table public.product_models enable row level security;
revoke all on table public.product_models from anon, authenticated;
grant select, insert, update, delete on table public.product_models to service_role;
grant usage, select on sequence public.product_models_id_seq to service_role;

create or replace function public.replace_product_models(p_product_id bigint, p_models jsonb)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not exists (select 1 from public.products where id = p_product_id) then
    raise exception 'Product % does not exist', p_product_id;
  end if;
  delete from public.product_models where product_id = p_product_id;
  insert into public.product_models (product_id, model, part_number, color, compatibility, availability, price, image, sort_order, is_active)
  select p_product_id, btrim(item.model), nullif(btrim(item.part_number), ''), nullif(btrim(item.color), ''),
    nullif(btrim(item.compatibility), ''), coalesce(nullif(item.availability, ''), 'on_request'),
    nullif(btrim(item.price), ''), nullif(btrim(item.image), ''), coalesce(item.sort_order, entry.ordinality - 1), coalesce(item.is_active, true)
  from jsonb_array_elements(coalesce(p_models, '[]'::jsonb)) with ordinality as entry(value, ordinality)
  cross join lateral jsonb_to_record(entry.value) as item(model text, part_number text, color text, compatibility text, availability text, price text, image text, sort_order integer, is_active boolean);
end;
$$;
revoke all on function public.replace_product_models(bigint, jsonb) from public, anon, authenticated;
grant execute on function public.replace_product_models(bigint, jsonb) to service_role;
