create table if not exists public.product_model_variants (
  id bigint generated by default as identity primary key,
  product_model_id bigint not null references public.product_models(id) on delete cascade,
  color text not null,
  part_number text not null,
  availability text not null default 'on_request',
  image text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_model_variants_color_not_blank check (btrim(color) <> ''),
  constraint product_model_variants_part_number_not_blank check (btrim(part_number) <> ''),
  constraint product_model_variants_availability_valid check (availability in ('in_stock', 'out_of_stock', 'on_request')),
  constraint product_model_variants_sort_order_nonnegative check (sort_order >= 0)
);

create unique index if not exists product_model_variants_model_color_ci_uidx
  on public.product_model_variants (product_model_id, lower(btrim(color)));
create index if not exists product_model_variants_model_sort_idx
  on public.product_model_variants (product_model_id, sort_order, id);
create index if not exists product_model_variants_part_number_idx
  on public.product_model_variants (part_number);
create index if not exists product_model_variants_active_model_sort_idx
  on public.product_model_variants (product_model_id, sort_order, id) where is_active;

alter table public.product_model_variants enable row level security;
revoke all on table public.product_model_variants from anon, authenticated;
grant select, insert, update, delete on table public.product_model_variants to service_role;
grant usage, select on sequence public.product_model_variants_id_seq to service_role;

create or replace function public.sync_product_models(p_product_id bigint, p_models jsonb)
returns void language plpgsql security definer set search_path = public as $$
declare
  model_entry record;
  variant_entry record;
  model_id bigint;
  variant_id bigint;
  kept_model_ids bigint[] := '{}';
  kept_variant_ids bigint[];
  is_laser_ink boolean;
begin
  select category = 'laser_inks' into is_laser_ink from public.products where id = p_product_id;
  if is_laser_ink is null then
    raise exception 'Product % does not exist', p_product_id;
  end if;

  for model_entry in
    select value, ordinality from jsonb_array_elements(coalesce(p_models, '[]'::jsonb)) with ordinality
  loop
    model_id := nullif(model_entry.value->>'id', '')::bigint;
    if model_id is null then
      insert into public.product_models (
        product_id, model, part_number, color, compatibility, availability, price, image, sort_order, is_active
      ) values (
        p_product_id,
        btrim(model_entry.value->>'model'),
        nullif(btrim(model_entry.value->>'part_number'), ''),
        nullif(btrim(model_entry.value->>'color'), ''),
        nullif(btrim(model_entry.value->>'compatibility'), ''),
        coalesce(nullif(model_entry.value->>'availability', ''), 'on_request'),
        case when is_laser_ink then null else nullif(btrim(model_entry.value->>'price'), '') end,
        nullif(btrim(model_entry.value->>'image'), ''),
        coalesce((model_entry.value->>'sort_order')::integer, model_entry.ordinality - 1),
        coalesce((model_entry.value->>'is_active')::boolean, true)
      ) returning id into model_id;
    else
      update public.product_models set
        model = btrim(model_entry.value->>'model'),
        part_number = nullif(btrim(model_entry.value->>'part_number'), ''),
        color = nullif(btrim(model_entry.value->>'color'), ''),
        compatibility = nullif(btrim(model_entry.value->>'compatibility'), ''),
        availability = coalesce(nullif(model_entry.value->>'availability', ''), 'on_request'),
        price = case when is_laser_ink then null else nullif(btrim(model_entry.value->>'price'), '') end,
        image = nullif(btrim(model_entry.value->>'image'), ''),
        sort_order = coalesce((model_entry.value->>'sort_order')::integer, model_entry.ordinality - 1),
        is_active = coalesce((model_entry.value->>'is_active')::boolean, true)
      where id = model_id and product_id = p_product_id;
      if not found then raise exception 'Model % does not belong to product %', model_id, p_product_id; end if;
    end if;

    kept_model_ids := array_append(kept_model_ids, model_id);
    kept_variant_ids := '{}';
    for variant_entry in
      select value, ordinality from jsonb_array_elements(coalesce(model_entry.value->'variants', '[]'::jsonb)) with ordinality
    loop
      variant_id := nullif(variant_entry.value->>'id', '')::bigint;
      if variant_id is null then
        insert into public.product_model_variants (
          product_model_id, color, part_number, availability, image, sort_order, is_active
        ) values (
          model_id,
          btrim(variant_entry.value->>'color'),
          btrim(variant_entry.value->>'part_number'),
          coalesce(nullif(variant_entry.value->>'availability', ''), 'on_request'),
          nullif(btrim(variant_entry.value->>'image'), ''),
          coalesce((variant_entry.value->>'sort_order')::integer, variant_entry.ordinality - 1),
          coalesce((variant_entry.value->>'is_active')::boolean, true)
        ) returning id into variant_id;
      else
        update public.product_model_variants set
          color = btrim(variant_entry.value->>'color'),
          part_number = btrim(variant_entry.value->>'part_number'),
          availability = coalesce(nullif(variant_entry.value->>'availability', ''), 'on_request'),
          image = nullif(btrim(variant_entry.value->>'image'), ''),
          sort_order = coalesce((variant_entry.value->>'sort_order')::integer, variant_entry.ordinality - 1),
          is_active = coalesce((variant_entry.value->>'is_active')::boolean, true),
          updated_at = now()
        where id = variant_id and product_model_id = model_id;
        if not found then raise exception 'Variant % does not belong to model %', variant_id, model_id; end if;
      end if;
      kept_variant_ids := array_append(kept_variant_ids, variant_id);
    end loop;

    delete from public.product_model_variants
    where product_model_id = model_id and not (id = any(kept_variant_ids));
  end loop;

  delete from public.product_models
  where product_id = p_product_id and not (id = any(kept_model_ids));
end;
$$;

revoke all on function public.sync_product_models(bigint, jsonb) from public, anon, authenticated;
grant execute on function public.sync_product_models(bigint, jsonb) to service_role;
